# Generated by Django 5.2.8 on 2025-11-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userinterestevaluation_userskillevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du métier (ex: Développeur Web)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du métier, des missions, etc.')),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Fourchette basse du salaire annuel brut (ex: 35000)', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Fourchette haute du salaire annuel brut (ex: 55000)', null=True)),
                ('required_skills', models.ManyToManyField(blank=True, help_text='Compétences requises pour ce métier', related_name='jobs', to='profiles.skill')),
            ],
        ),
    ]
