# Generated by Django 5.2.8 on 2025-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="relevant_interests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Intérêts pertinents pour ce métier",
                related_name="jobs_by_interest",
                to="profiles.interest",
            ),
        ),
    ]
