# Generated by Django 5.2.8 on 2025-12-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("profiles", "0004_job_relevant_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                default=1,
                help_text="L'entreprise qui publie cette fiche de poste",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="companies.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                help_text="Titre du métier (ex: Développeur Web)", max_length=200
            ),
        ),
    ]
