# Generated by Django 5.2.8 on 2025-12-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_job_created_at_job_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la formation"
                    ),
                ),
                (
                    "school",
                    models.CharField(max_length=200, verbose_name="Établissement"),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="Ex: Bac+3, Master, Doctorat, Certification...",
                        max_length=50,
                        verbose_name="Niveau d'études",
                    ),
                ),
                (
                    "duration_in_years",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Durée (en années)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="formations",
            field=models.ManyToManyField(
                blank=True,
                to="profiles.formation",
                verbose_name="Formations recommandées",
            ),
        ),
    ]
