# Generated by Django 6.0.1 on 2026-01-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_formation_job_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, help_text='Téléchargez votre CV au format PDF.', null=True, upload_to='cvs/', verbose_name='curriculum vitae (CV)'),
        ),
    ]
