# Generated by Django 6.0.1 on 2026-01-30 15:26

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, help_text='Téléchargez votre CV au format PDF.', null=True, upload_to='cvs/', validators=[profiles.models.validate_file_extension], verbose_name='curriculum vitae (CV)'),
        ),
    ]
