# Generated by Django 6.0.1 on 2026-01-31 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_joboffer'),
        ('profiles', '0009_alter_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.joboffer')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.profile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student_profile', 'job_offer')},
            },
        ),
    ]
