# Generated by Django 6.0.1 on 2026-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='formations',
        ),
        migrations.RemoveField(
            model_name='job',
            name='relevant_interests',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='students', to='profiles.formation', verbose_name='Formations suivies'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
