# Generated by Django 6.0.1 on 2026-01-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_job_company_remove_job_formations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='formations',
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, help_text='Ex: Bac+3, Master, Doctorat', max_length=50, verbose_name="Niveau d'études actuel/obtenu"),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_preference',
            field=models.CharField(blank=True, help_text="Ex: Paris, France ou 'Télétravail'", max_length=150, verbose_name='Lieu de travail souhaité'),
        ),
    ]
