# Generated by Django 6.0.1 on 2026-01-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_industry_and_more'),
        ('profiles', '0009_alter_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('offer_type', models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi(CDD, CDI...)'), ('alternance', 'Alternance'), ('full_time', 'Temps plein'), ('part_time', 'Temps partiel')], default='emploi', max_length=20, verbose_name='Type de contrat')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.company', verbose_name='Entreprise')),
                ('required_skills', models.ManyToManyField(blank=True, to='profiles.skill', verbose_name='Compétences requises')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
