# Generated by Django 6.0.1 on 2026-01-31 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_joboffer'),
        ('profiles', '0011_remove_job_company_remove_job_formations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='offer_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi (CDD, CDI...)'), ('alternance', 'Alternance'), ('full_time', 'Temps plein'), ('part_time', 'Temps partiel')], default='emploi', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Lettre de motivation')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.joboffer', verbose_name="Offre d'emploi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.profile', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
                'unique_together': {('job_offer', 'student')},
            },
        ),
    ]
