# Generated by Django 6.0.1 on 2026-01-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_joboffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='required_education_level',
            field=models.CharField(blank=True, help_text='Ex: Bac+3, Master, Certification', max_length=50, verbose_name="Niveau d'études minimum requis"),
        ),
    ]
