# Generated by Django 5.2.8 on 2025-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Étudiant"), ("company", "Entreprise")],
                default="student",
                help_text="Type d'utilisateur (étudiant ou entreprise)",
                max_length=10,
            ),
        ),
    ]
